name: Publish pkg.pr.new

on:
  workflow_dispatch:
  pull_request:

env:
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'
  
  version: '2.1'
 orbs:
  node: circleci/node@x.y
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-bun:
          version: 1.2.22
      - node/install-packages:
          pkg-manager: bun
      - run: bun run test
workflows:
  test_my_app:
    jobs:
      - test


